name: API

on:
  push:
    branches:
      - main
    paths:
      - api/**
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: api/Dockerfile
          context: api
          push: true
          tags: ghcr.io/djoamersfoort/media/api:latest

      - name: Redeploy
        run: |
          curl https://portainer.djoamersfoort.nl/hooks/update-docker-image?stack=media_djoamersfoort_nl -H "X-Token: ${{ secrets.WEBHOOK_TOKEN }}"
      
      - name: Clean up old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'media/api'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
